-- (1) public.users 테이블, supabase auth 테이블 연동
CREATE TABLE IF NOT EXISTS public.users
(
    id         uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email      text,
    nickname   text,
    created_at timestamp with time zone DEFAULT timezone('utc', now()),
    is_active  boolean                  DEFAULT true
);

-- (2) 트리거 함수
CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS
$$
BEGIN
    INSERT INTO public.users (id, email, nickname, created_at)
    VALUES (NEW.id,
            NEW.email,
            NEW.raw_user_meta_data->>'nickname',
            timezone('utc', now()));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- (3) 트리거
CREATE TRIGGER on_auth_user_created
    AFTER INSERT
    ON auth.users
    FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user();

create table if not exists public.posts
(
    title         text                     not null,
    created_at    timestamp with time zone not null,
    content       text                     not null,
    user_id       uuid                     not null
        references public.users
            on delete cascade,
    id            bigint generated by default as identity,
    thumbnail_url text,
    modified_at   timestamp with time zone,
    deleted_at    timestamp with time zone
);


create table if not exists public.post_likes
(
    post_id    bigint not null
        references public.posts
            on delete cascade,
    user_id    uuid   not null
        references public.users
            on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    primary key (post_id, user_id)
);
